version: '3'
services:
  icarus:
    image: randyherban/icarus:latest
    build:
      context: /opt/radiohound/icarus
      dockerfile: /opt/radiohound/docker/icarus-Dockerfile
    volumes:
      - ./icarus/system.json:/opt/radiohound/icarus/system.json
    network_mode: "host"
    container_name: "icarus"
    restart: unless-stopped

  radiohound_web:
    image: randyherban/radiohound_web:latest
    build:
      context: /opt/radiohound/radiohound_web
      dockerfile: /opt/radiohound/docker/radiohound_web-Dockerfile
    network_mode: "host"
    container_name: "radiohound_web"
    restart: unless-stopped

  radiohound_app:
    image: randyherban/radiohound_app:latest
    build:
      context: /opt/radiohound/radiohound_app
      dockerfile: /opt/radiohound/docker/radiohound_app-Dockerfile
    network_mode: "host"
    container_name: "radiohound_app"
    restart: unless-stopped

  mqtt:
    image: "eclipse-mosquitto"
    container_name: "mqtt"
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb:
    image: "mongodb/mongodb-community-server"
    container_name: "mongodb"
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
        - mongodb:/data/db
    env_file: ".env"
    networks:
      - mongodb

  fft:
    image: randyherban/fft:latest
    build:
      context: /opt/radiohound/docker/fft
      dockerfile: /opt/radiohound/docker/fft/Dockerfile
    container_name: fft
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/ringbuffer:/data/ringbuffer


volumes:
    mongodb:

networks:
  mongodb: